version: '3'

services:
  # Configuración del NameNode de Hadoop
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"  # Interfaz web de Hadoop
      - "8020:8020" 
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop_network
    depends_on:
      - zookeeper
      - kafka
  # Configuración del DataNode de Hadoop
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9864:9864"  # Puerto DataNode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoop_network
    depends_on:
      - namenode
  # Configuración de Zookeeper (para Kafka)
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"  # Puerto Zookeeper
    networks:
      - hadoop_network

  # Configuración de Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-new
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME_INTERNAL=INTERNAL
      - KAFKA_LISTENER_PORT_INTERNAL=9093
    ports:
      - "9092:9092"  # Puerto Kafka
    networks:
      - hadoop_network
    depends_on:
      - zookeeper
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "5601:5601"

# Volúmenes de datos de Hadoop
volumes:
  hadoop_namenode:
  hadoop_datanode:

# Redes
networks:
  hadoop_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24